### ISSUE TITLE
Test fails due to incomplete specification of random seed (RNGkind)

### ISSUE THREAD

**Issue by shikokuchuo** [wlandau/crew#112]
## Prework

* [x] Read and agree to the [Contributor Code of Conduct](https://github.com/wlandau/crew/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/ropensci/crew/blob/main/CONTRIBUTING.md).

## Description

`mirai` 0.9.1.9019 would break `crew` tests if not for a workaround .onLoad hook which sets the RNGkind to "L'Ecuyer-CMRG" if `crew` is detected. This is not wrong, but also not necessary.

https://github.com/shikokuchuo/mirai/blob/d6b1cfafc0460ae57a17fdaba6ece35182d5d52f/R/mirai-package.R#L65C1-L66C34

The failing test is:
https://github.com/wlandau/crew/blob/0bf1273e6ed14c334dd75ba684dabee1a4d70465/tests/testthat/test-crew_controller_local.R#L100

This is because in creating the local variable `exp`, you just use `set.seed(0L)` on line 97 without specifying the RNGkind. The worker is now using  "L'Ecuyer-CMRG" hence leading to a mismatch. A statement `RNGkind("L'Ecuyer-CMRG")` in the testthat script would be one solution.

I think currently the plan is that `mirai` is released prior to `crew`, so it might have to go out with the workaround unless you can think of something better. Once the test is fixed I can then remove this.

Happy to provide background on the changes separately / on a call.

**Comment by wlandau** [comment]
Thanks for the FYI. I think this should be fixed in https://github.com/wlandau/crew/commit/5cfd9046a378aca811d46e217569dd388e852d98. However, that part of the test is already suppressed on CRAN via the `NOT_CRAN` envvar, so I don't think it will impact either of our release cycles.

https://github.com/wlandau/crew/blob/5cfd9046a378aca811d46e217569dd388e852d98/tests/testthat/test-crew_controller_local.R#L82-L84

Curious as to the motivation for L'Ecuyer-CMRG, given how popular and successful Mersenne-Twister is. Did you notice a performance difference?

**Comment by shikokuchuo** [comment]
FYI I have provided further explanation on the motivation in #113
