### ISSUE TITLE
Add a substitute argument to push()

### ISSUE THREAD

**Issue by wlandau** [wlandau/crew#63]
Analogous to `future::future()`. Default should probably be `TRUE`.

**Comment by shikokuchuo** [comment]
With this change: https://github.com/shikokuchuo/mirai/issues/49#issuecomment-1498715182

Your substitute argument becomes redundant and can be reverted.

**Comment by wlandau** [comment]
I updated `crew` to trust `mirai` to recognize language objects. However, I still prefer `substitute` for `crew`. On reason is that I deparse the command as text and make it available for the user to see later. I also prefer to be pedantic about the types of arguments to `crew` functions. It would be rare for the user to supply e.g. `quote(x + y)` and want `substitute = TRUE`, but I prefer even this situation to be unambiguous.

**Comment by wlandau** [comment]
Thanks for explaining your thinking. I do not share the same opinion about how to treat symbol arguments (I think users may want to test `mirai()` using a trivial command that just returns an element of the data), but you make good points. (NB the symbol scenario does affect `crew` because `crew` only sends calls to `crew_eval()`.)

**Comment by shikokuchuo** [comment]
You make a good point - it is possible that someone wants to test mirai with something like `mirai(x, x = 1)`, and `x` also happens to be a language object in the calling environment.

But now we are talking about probabilities - the joint probability that (i) there exists a language object (not any other type of object) on the search path with the exact same name as the arbitrary symbol specified, and that (ii) the real intention of the mirai is to just evaluate the symbol (which is kind of pointless for a mirai).

So that's why I am willing to make this assumption.

Sorry for being long-winded - I just want to make sure my logic is correct, as this discovery is fairly recent.
